name: Red Letter Day
markdown: kramdown
permalink: /:title
github: [metadata]

# Pagination
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "page:num/"

# jekyll-seo-tag plugin stuff
plugins:
    - jekyll-seo-tag
title: Red Letter Day
description: A San Francisco based personal blog about city living, motherhood, and real life. Hi there, I’m Tiffany. An Idaho girl living in the heart of San Francisco with my husband and baby. I believe in living life simply and mindfully. I’ve always loved to write. And I hope you like to read. 
author: Tiffany Turley
social:
  name: Tiffany Turley
  links:
    - https://www.instagram.com/totiffany
    - https://www.etsy.com/people/totiffanyann

